server:
  port: 4002

spring:
  application:
    name: restaurant-service
  data:
    mongodb:
      uri: mongodb+srv://${MONGODB_ATLAS_USER}:${MONGODB_ATLAS_PASSWORD}@${MONGODB_ATLAS_HOST}/${MONGODB_DATABASE:restaurant-db}?retryWrites=true&w=majority&appName=Cluster0

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
