server:
  port: 4003

spring:
  application:
    name: reservation-service

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
